### ISSUE TITLE
Robot Texture not loading in RobotCoral v0.2.3

### ISSUE THREAD

**Issue by hoersamu** [robotcoral/coral-app#282]
**Describe the bug**
Three.js GLTF loader can't load texture.
This is because the blob: tag in nginx.conf is set behind the wrong variable.

**To Reproduce**
just open https://editor.robotcoral.de

**Expected behavior**
The Robottexture should be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/14295796/136916015-90249c34-aff5-4692-a883-b946269328e8.png)

**Proposed Fix**
Move the blob: tag in nginx behind the correct property.

**Comment by hoersamu** [comment]
Hm must be a problem on my side then.
Can you check it works in chrome on mobile on your devices?

**Comment by twihno** [comment]
fixed in #348
