### ISSUE TITLE
Setup proper ci/cd pipeline

### ISSUE THREAD

**Issue by hoersamu** [robotcoral/coral-app#34]
My plan:
All pulls on dev trigger a "nightly" docker build that gets deployed to a subdomain.(nightly. or dev.robotcoral.de)
All pulls on master trigger a build that will be deployed to the actual domain.

@twihno could you setup the docker stuff this weekend? I'll work on the automatic deployment

**Comment by hoersamu** [comment]
single channel deployment works but dual channel still needs to be implemented

**Comment by twihno** [comment]
- [x] nightly build
- [x ] auto code formatting

**Comment by twihno** [comment]
- [ ] move dev.robotcoral.de to nightly build
@hoersamu

**Comment by twihno** [comment]
- [ ] Merge bump-version commit into dev branch after creating a release

**Comment by twihno** [comment]
yes
