### ISSUE TITLE
Lengths can be set to 0, if below zero the program doesn't respond.

### ISSUE THREAD

**Issue by Hyruleh3ro** [robotcoral/coral-app#65]
![Screenshot (340)](https://user-images.githubusercontent.com/73059478/130981386-b6dfbc7f-9ff4-4fcc-b476-226ea18e9d11.png)

![Screenshot (342)](https://user-images.githubusercontent.com/73059478/130982630-a4705bae-2495-456c-8de6-0ade4759f075.png)

Worlds with a length or width of zero can be constructed, but don't work in any direction. If the value is set to be below zero the program doesn't react.

To Reproduce:
 1. Create world with a height, length or width of zero.
 2.1. If the height is set to zero: try putting down black and red blocks. Only the black blocks will be able to be put down.
 2.2. If the length or width is set to zero movement is impossible.

Additional suggestion:
If a value of below zero is used for the world construction the program just refuses to continue. An answer or an error message would be helpful.

**Comment by hoersamu** [comment]
why did you reopen this?
